disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = ""

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/VLC.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "VictoryLuode"
  image = "img/VictoryLuodeProf.png"
  headline = " ###### Youtube大学毕业生"
  bio = "CG Artist"
  links = [
  { email = "mailto:victoryluode@outlook.com" },
  { bilibili = "https://space.bilibili.com/176090455?spm_id_from=333.1007.0.0" },
  { instagram = "https://www.instagram.com/victoryluode/" },
  { artstation = "https://www.artstation.com/victoryluode" },
  { twitter = "https://twitter.com/VictoryLuode" },
  { youtube = "https://www.youtube.com/victoryluode" },
  { tiktok = "https://www.tiktok.com/@victoryluode" },
  
]